---
- name: Install Apache and MySQL
  hosts: all
  become: true
  tasks:
    - name: Install Apache
      package:
        name: httpd
        state: present
      when: "'webservers' in group_names"

    - name: Install MySQL
      package:
        name: mysql
        state: present
      when: "'dbservers' in group_names"


