---
# tasks file for hw3-role
- name: Install and start Apache
  hosts: webservers
  become: true
  tasks:
    - name: Install Apache package
      package:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: true

- name: Install MySQL, create database, and update packages
  hosts: dbservers
  become: true
  tasks:
    - name: Install MySQL package
      package:
        name: mysql
        state: present

    - name: Start MySQL service
      service:
       name: mysqld  # or mysql, mariadb, mysql-server, mysql-<version>, mariadb-<version>
       state: started
       enabled: true


    - name: Create database
      mysql_db:
        name: test
        state: present

    - name: Update all packages except php, python, kernel
      yum:
        name: '*'
        state: latest
        exclude: php*, python*, kernel*
        update_cache: yes

- name: Stop services, update, and reboot VMs
  hosts: all
  become: true
  tasks:
    - name: Stop Apache and MySQL services
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - httpd
        - mysqld

    - name: Update all packages except php, python, kernel
      yum:
        name: '*'
        state: latest
        exclude: php*, python*, kernel*
        update_cache: yes

    - name: Reboot VMs
      reboot:
        reboot_timeout: 300
        reboot_delay: 30
        test_command: uptime

- name: Restart MariaDB service on dbservers
  hosts: dbservers
  become: true
  tasks:
    - name: Restart MariaDB service
      service:
        name: mysqld
        state: restarted

